language: python
sudo: false
python:
  - "2.7"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install -r requirements-dev.txt
  - travis_retry python setup.py develop
  - travis_retry pip install python-coveralls
script: py.test
after_success:
  - coveralls
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
    - $HOME/.theano
